### ISSUE TITLE
Use placeholder API key

### ISSUE THREAD

**Issue by bukinoshita** [lancer-code/next-glactic#2]
I don't know if this API key is still valid or not, but it would be good to not expose real API keys and use a placeholder one or add behind an environment variable.

If it's a valid API key, I'd also recommend going into resend and rotate that API key.

https://github.com/lancer-code/next-glactic/blob/e3c1a95be07c879b78e978ffa6caf08caa766998/src/app/lib/resend.ts#L3

**Comment by lancer-code** [comment]
Hi, Thanks for pointing that out. I was just debugging it, as it was not loading from the .env file, so I put it here temporarily and forgot.

The problem is the API key loading but it's not sending the email, nothing on the Resend Email Dashboard and not showing any error.

I don't know what's going on.

Well I Revoke the key so its good to go
